---
- name: Upload Relay Server to Host
  hosts: 
    - outsidepi
  become: yes

  tasks:
    - name: Copy pi driver directory
      copy:
        src: ../pi-drivers/
        dest: /home/pi/relay-switcher/
    - name: Make executable
      command: "chmod +x /home/pi/relay-switcher/main.py"
- name: Update service file
  hosts: 
    - outsidepi
  become: yes

  tasks:
    - name: Copy pi driver init Serivce to host
      copy:
        src: ../scripts/xmas.service
        dest: /etc/systemd/system/xmas.service
- name: Restart RelayBackend
  hosts: 
    - outsidepi
  become: yes

  tasks:
    - name: daemon reload
      command: "sudo systemctl daemon-reload"

    - name: daemon enable 
      command: "sudo systemctl enable xmas.service"

    - name: daemon start
      command: "sudo systemctl restart xmas.service"
