parameters: {}
environment: {}
packages:
  - name: timer-function
    parameters: {}
    environment: {}
    actions:
      - name: relayZero
        main: '' 
        runtime: 'go:default'
        parameters: {}
        environment: {}

