#- name: Test rpiBackend 
#run: go test -v ./...

name: Build and Deploy rpiBackend

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      working-directory: ./relaySwitcher
      with:
        go-version: 1.18
    - name: Build rpiBackend 
        run: go build -v ./...
    - name: deploy
      uses: kc8/sftp-upload@v0.04
      with:
        host: ${{ secrets.D_ADDR }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        paths: '{"relaySwitcherAddMessage": "/home/rpiBackend"}'
